export const dots = [
    { id: 'child1', href: '#', top: 51.5, left: 1.25, title: 'CLoud Nine', location: 'Siargao', country: 'Philippines', surf: '9 - 13', tide: '+2.3', wind: '4 SE', image: '/surf/images/surf/1.jpg', airline: 'Virgin Philippines', airlineLogo: 'surf/images/travel/virgin.png' },
    { id: 'child2', href: '#', top: 45.5, left: 13, title: 'Vieux Boucau', location: 'Hossegor', country: 'France', surf: '14 - 21', tide: '+4.2', wind: '6 SE', image: '/surf/images/surf/2.jpg', airline: 'Virgin France', airlineLogo: 'surf/images/travel/virgin.png' },
    { id: 'child3', href: '#', top: 50.2, left: 29.2, title: 'Some1 Beach', location: 'Moscow', country: 'Russia', surf: '14 - 21', tide: '+4.2', wind: '6 SE', image: '/surf/images/surf/3.jpg', airline: 'Virgin France', airlineLogo: 'surf/images/travel/virgin.png' },
    { id: 'child4', href: '#', top: 79, left: 35, title: 'Some2 Beach', location: 'Phuket', country: 'Thailand', surf: '14 - 21', tide: '+4.2', wind: '6 SE', image: '/surf/images/surf/4.jpg', airline: 'Virgin Thailand', airlineLogo: 'surf/images/travel/virgin.png' },
    { id: 'child5', href: '#', top: 34, left: 44.5, title: 'Some3 Beach', location: 'Bali', country: 'indonesia', surf: '14 - 21', tide: '+4.2', wind: '6 SE', image: '/surf/images/surf/1.jpg', airline: 'Virgin indonesia', airlineLogo: 'surf/images/travel/virgin.png' },
    { id: 'child6', href: '#', top: 87.5, left: 52.7, title: 'Some4 Beach', location: 'Kamchatka', country: 'Russia', surf: '14 - 21', tide: '+4.2', wind: '6 SE', image: '/surf/images/surf/2.jpg', airline: 'Virgin Russia', airlineLogo: 'surf/images/travel/virgin.png' },
    { id: 'child7', href: '#', top: 62, left: 66, title: 'Malibu Beach', location: 'California', country: 'Usa', surf: '14 - 21', tide: '+4.2', wind: '6 SE', image: '/surf/images/surf/3.jpg', airline: 'Virgin Usa', airlineLogo: 'surf/images/travel/virgin.png' },
    { id: 'child8', href: '#', top: 79, left: 88.7, title: 'Airlie Beach', location: 'Queensland', country: 'Australia', surf: '14 - 21', tide: '+4.2', wind: '6 SE', image: '/surf/images/surf/4.jpg', airline: 'Virgin Australia', airlineLogo: 'surf/images/travel/virgin.png' },
];