name: Deploy to Server

on:
  push:
    branches:
      - main  # измените на нужную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DIRECTUS_URL: https://directus.mfkdev.ru
      DIRECTUS_EMAIL: mfksky@icloud.com
      DIRECTUS_PASSWORD: mainloginDIRECTUSPORTFOLIO1905!
      PUBLIC_DIRECTUS_URL: https://directus.mfkdev.ru

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy files via SSH
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/ user@yourserver:/var/www/yourdomain.com/html

    - name: Restart Nginx
      run: |
        ssh -o StrictHostKeyChecking=no user@yourserver "sudo systemctl reload nginx"
