name: Deploy to Server

on:
  push:
    branches:
      - main  # измените на нужную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DIRECTUS_URL: ${{ secrets.DIRECTUS_URL }}
      DIRECTUS_EMAIL: ${{ secrets.DIRECTUS_EMAIL }}
      DIRECTUS_PASSWORD: ${{ secrets.DIRECTUS_PASSWORD }}
      PUBLIC_DIRECTUS_URL: ${{ secrets.PUBLIC_DIRECTUS_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy files via SSH
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/ root@147.45.246.185:/var/www/mfkdev.ru/html

    - name: Restart Nginx
      run: |
        ssh -o StrictHostKeyChecking=no root@147.45.246.185 "sudo systemctl reload nginx"
